-- TEMO - Grupos de transacciones y arqueos de efectivo por cliente.
-- Esta migracion es idempotente y conserva las transacciones existentes.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
SET search_path TO temo, public;

DO $$ BEGIN
  CREATE TYPE estado_grupo_transacciones AS ENUM ('ABIERTO', 'COMPLETADO', 'ANULADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE tipo_tasa_aplicada AS ENUM ('COMPRA', 'VENTA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TYPE tipo_arqueo ADD VALUE IF NOT EXISTS 'TRANSACCION_RECIBIDO';
ALTER TYPE tipo_arqueo ADD VALUE IF NOT EXISTS 'TRANSACCION_ENTREGADO';
ALTER TYPE tipo_arqueo ADD VALUE IF NOT EXISTS 'TRANSACCION_VUELTO';

-- Compatibilidad con instalaciones antiguas que guardaban una sola sucursal en la cuenta.
CREATE TABLE IF NOT EXISTS cuentas_sucursales (
  id_cuenta UUID NOT NULL
    REFERENCES cuentas_bancarias(id_cuenta) ON DELETE CASCADE,
  id_sucursal UUID NOT NULL
    REFERENCES sucursales(id_sucursal) ON DELETE CASCADE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id_cuenta, id_sucursal)
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'temo'
      AND table_name = 'cuentas_bancarias'
      AND column_name = 'id_sucursal'
  ) THEN
    EXECUTE '
      INSERT INTO cuentas_sucursales (id_cuenta, id_sucursal)
      SELECT id_cuenta, id_sucursal
      FROM cuentas_bancarias
      WHERE id_sucursal IS NOT NULL
      ON CONFLICT (id_cuenta, id_sucursal) DO NOTHING
    ';
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_cuentas_sucursales_sucursal
  ON cuentas_sucursales(id_sucursal);

-- Compatibilidad con reglas fijas creadas antes de separar la moneda de comision.
ALTER TABLE reglas_comisiones
  ADD COLUMN IF NOT EXISTS id_moneda_comision UUID
    REFERENCES monedas(id_moneda);

-- Los datos comunes del cliente y de la liquidacion viven una sola vez por grupo.
CREATE TABLE IF NOT EXISTS grupos_transacciones (
  id_grupo_transacciones UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo_operacion BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  id_turno UUID NOT NULL REFERENCES turnos(id_turno),
  id_contraparte UUID REFERENCES contrapartes(id_contraparte),
  estado estado_grupo_transacciones NOT NULL DEFAULT 'ABIERTO',
  id_tipo_cambio_vuelto UUID REFERENCES tipos_cambio(id_tipo_cambio),
  tipo_tasa_vuelto tipo_tasa_aplicada,
  tasa_vuelto_usada NUMERIC(14, 6) CHECK (tasa_vuelto_usada IS NULL OR tasa_vuelto_usada > 0),
  observaciones TEXT,
  id_usuario_creacion UUID NOT NULL REFERENCES usuarios(id_usuario),
  id_usuario_modificacion UUID REFERENCES usuarios(id_usuario),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_grupos_tasa_vuelto CHECK (
    (tipo_tasa_vuelto IS NULL AND tasa_vuelto_usada IS NULL)
    OR (tipo_tasa_vuelto IS NOT NULL AND tasa_vuelto_usada IS NOT NULL)
  )
);

ALTER TABLE transacciones
  ADD COLUMN IF NOT EXISTS id_grupo_transacciones UUID,
  ADD COLUMN IF NOT EXISTS orden_grupo SMALLINT;

-- Cada transaccion historica se convierte en un grupo unitario sin cambiar su identidad.
INSERT INTO grupos_transacciones (
  id_grupo_transacciones,
  id_turno,
  id_contraparte,
  estado,
  id_usuario_creacion,
  id_usuario_modificacion,
  fecha_creacion,
  fecha_modificacion
)
SELECT
  t.id_transaccion,
  t.id_turno,
  t.id_contraparte,
  CASE
    WHEN t.estado = 'ANULADA' THEN 'ANULADO'::estado_grupo_transacciones
    ELSE 'COMPLETADO'::estado_grupo_transacciones
  END,
  t.id_usuario_creacion,
  t.id_usuario_modificacion,
  t.fecha_creacion,
  t.fecha_modificacion
FROM transacciones t
WHERE t.id_grupo_transacciones IS NULL
ON CONFLICT (id_grupo_transacciones) DO NOTHING;

UPDATE transacciones
SET id_grupo_transacciones = id_transaccion,
    orden_grupo = 1
WHERE id_grupo_transacciones IS NULL;

WITH ordenes_faltantes AS (
  SELECT
    id_transaccion,
    row_number() OVER (
      PARTITION BY id_grupo_transacciones
      ORDER BY fecha_transaccion, id_transaccion
    )::SMALLINT AS orden_calculado
  FROM transacciones
  WHERE orden_grupo IS NULL
)
UPDATE transacciones t
SET orden_grupo = o.orden_calculado
FROM ordenes_faltantes o
WHERE o.id_transaccion = t.id_transaccion;

DO $$ BEGIN
  ALTER TABLE transacciones
    ADD CONSTRAINT fk_transacciones_grupo
    FOREIGN KEY (id_grupo_transacciones)
    REFERENCES grupos_transacciones(id_grupo_transacciones);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE transacciones
  ALTER COLUMN id_grupo_transacciones SET NOT NULL,
  ALTER COLUMN orden_grupo SET NOT NULL;

DO $$ BEGIN
  ALTER TABLE transacciones
    ADD CONSTRAINT ck_transacciones_orden_grupo CHECK (orden_grupo > 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_transacciones_grupo_orden
  ON transacciones(id_grupo_transacciones, orden_grupo);

CREATE OR REPLACE FUNCTION validar_turno_grupo_transaccion()
RETURNS TRIGGER AS $$
DECLARE
  v_id_turno_grupo UUID;
BEGIN
  SELECT id_turno
  INTO v_id_turno_grupo
  FROM grupos_transacciones
  WHERE id_grupo_transacciones = NEW.id_grupo_transacciones;

  IF v_id_turno_grupo IS DISTINCT FROM NEW.id_turno THEN
    RAISE EXCEPTION
      'La transaccion y su grupo deben pertenecer al mismo turno';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validar_turno_grupo_transaccion ON transacciones;
CREATE TRIGGER trg_validar_turno_grupo_transaccion
BEFORE INSERT OR UPDATE OF id_turno, id_grupo_transacciones
ON transacciones
FOR EACH ROW
EXECUTE FUNCTION validar_turno_grupo_transaccion();

-- Arqueos se amplia para aceptar como alcance un grupo de transacciones.
ALTER TABLE arqueos
  ADD COLUMN IF NOT EXISTS id_grupo_transacciones UUID
    REFERENCES grupos_transacciones(id_grupo_transacciones) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS id_tipo_cambio UUID REFERENCES tipos_cambio(id_tipo_cambio),
  ADD COLUMN IF NOT EXISTS tipo_tasa tipo_tasa_aplicada,
  ADD COLUMN IF NOT EXISTS tasa_usada NUMERIC(14, 6),
  ADD COLUMN IF NOT EXISTS monto_esperado NUMERIC(16, 4);

ALTER TABLE arqueos
  DROP CONSTRAINT IF EXISTS ck_arqueos_alcance;

DO $$ BEGIN
  ALTER TABLE arqueos
    ADD CONSTRAINT ck_arqueos_alcance
    CHECK (num_nonnulls(id_turno, id_jornada, id_grupo_transacciones) = 1);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE arqueos
    ADD CONSTRAINT ck_arqueos_tasa
    CHECK (
      (tipo_tasa IS NULL AND tasa_usada IS NULL)
      OR (tipo_tasa IS NOT NULL AND tasa_usada IS NOT NULL AND tasa_usada > 0)
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE arqueos
    ADD CONSTRAINT ck_arqueos_monto_esperado
    CHECK (monto_esperado IS NULL OR monto_esperado >= 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE arqueos
  DROP CONSTRAINT IF EXISTS ck_arqueos_transaccion;

ALTER TABLE arqueos
  ADD CONSTRAINT ck_arqueos_transaccion
  CHECK (
    (
      tipo IN (
        'TRANSACCION_RECIBIDO',
        'TRANSACCION_ENTREGADO',
        'TRANSACCION_VUELTO'
      )
      AND id_grupo_transacciones IS NOT NULL
      AND monto_esperado IS NOT NULL
      AND tipo_tasa IS NOT NULL
      AND tasa_usada IS NOT NULL
    )
    OR
    (
      tipo NOT IN (
        'TRANSACCION_RECIBIDO',
        'TRANSACCION_ENTREGADO',
        'TRANSACCION_VUELTO'
      )
      AND id_grupo_transacciones IS NULL
    )
  );

ALTER TABLE arqueos
  ADD COLUMN IF NOT EXISTS diferencia NUMERIC(16, 4)
  GENERATED ALWAYS AS (monto_total - COALESCE(monto_esperado, monto_total)) STORED;

CREATE UNIQUE INDEX IF NOT EXISTS uq_arqueos_grupo_tipo_moneda
  ON arqueos(id_grupo_transacciones, tipo, id_moneda)
  WHERE id_grupo_transacciones IS NOT NULL;

-- El detalle conserva la metodologia operativa de montones de 25 y sueltos.
ALTER TABLE arqueos_denominaciones
  ADD COLUMN IF NOT EXISTS montones_25 INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sueltos INTEGER NOT NULL DEFAULT 0;

UPDATE arqueos_denominaciones
SET sueltos = cantidad
WHERE montones_25 = 0
  AND sueltos = 0
  AND cantidad > 0;

DO $$ BEGIN
  ALTER TABLE arqueos_denominaciones
    ADD CONSTRAINT ck_arqueos_denominaciones_montones CHECK (montones_25 >= 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE arqueos_denominaciones
    ADD CONSTRAINT ck_arqueos_denominaciones_sueltos CHECK (sueltos >= 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE OR REPLACE FUNCTION preparar_arqueo_denominacion()
RETURNS TRIGGER AS $$
DECLARE
  v_valor NUMERIC(14, 2);
  v_moneda_denominacion UUID;
  v_moneda_arqueo UUID;
BEGIN
  SELECT valor, id_moneda
  INTO v_valor, v_moneda_denominacion
  FROM denominaciones
  WHERE id_denominacion = NEW.id_denominacion;

  SELECT id_moneda
  INTO v_moneda_arqueo
  FROM arqueos
  WHERE id_arqueo = NEW.id_arqueo;

  IF v_moneda_denominacion IS DISTINCT FROM v_moneda_arqueo THEN
    RAISE EXCEPTION 'La denominacion y el arqueo deben pertenecer a la misma moneda';
  END IF;

  -- Compatibilidad con clientes antiguos que solo insertaban o actualizaban cantidad.
  IF TG_OP = 'UPDATE'
     AND NEW.montones_25 IS NOT DISTINCT FROM OLD.montones_25
     AND NEW.sueltos IS NOT DISTINCT FROM OLD.sueltos
     AND NEW.cantidad IS DISTINCT FROM OLD.cantidad THEN
    NEW.montones_25 = 0;
    NEW.sueltos = NEW.cantidad;
  ELSIF NEW.montones_25 = 0 AND NEW.sueltos = 0 AND NEW.cantidad > 0 THEN
    NEW.sueltos = NEW.cantidad;
  END IF;

  NEW.cantidad = NEW.montones_25 * 25 + NEW.sueltos;
  NEW.monto = NEW.cantidad * v_valor;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_preparar_arqueo_denominacion ON arqueos_denominaciones;
CREATE TRIGGER trg_preparar_arqueo_denominacion
BEFORE INSERT OR UPDATE OF id_arqueo, id_denominacion, montones_25, sueltos, cantidad
ON arqueos_denominaciones
FOR EACH ROW
EXECUTE FUNCTION preparar_arqueo_denominacion();

CREATE OR REPLACE FUNCTION recalcular_total_arqueo()
RETURNS TRIGGER AS $$
DECLARE
  v_id_arqueo UUID;
BEGIN
  v_id_arqueo := COALESCE(NEW.id_arqueo, OLD.id_arqueo);

  UPDATE arqueos
  SET monto_total = (
    SELECT COALESCE(sum(monto), 0)
    FROM arqueos_denominaciones
    WHERE id_arqueo = v_id_arqueo
  )
  WHERE id_arqueo = v_id_arqueo;

  IF TG_OP = 'UPDATE' AND OLD.id_arqueo IS DISTINCT FROM NEW.id_arqueo THEN
    UPDATE arqueos
    SET monto_total = (
      SELECT COALESCE(sum(monto), 0)
      FROM arqueos_denominaciones
      WHERE id_arqueo = OLD.id_arqueo
    )
    WHERE id_arqueo = OLD.id_arqueo;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_recalcular_total_arqueo ON arqueos_denominaciones;
CREATE TRIGGER trg_recalcular_total_arqueo
AFTER INSERT OR UPDATE OR DELETE
ON arqueos_denominaciones
FOR EACH ROW
EXECUTE FUNCTION recalcular_total_arqueo();

DROP TRIGGER IF EXISTS trg_grupos_transacciones_fecha_modificacion ON grupos_transacciones;
CREATE TRIGGER trg_grupos_transacciones_fecha_modificacion
BEFORE UPDATE ON grupos_transacciones
FOR EACH ROW
EXECUTE FUNCTION actualizar_fecha_modificacion();

CREATE INDEX IF NOT EXISTS idx_grupos_transacciones_turno_fecha
  ON grupos_transacciones(id_turno, fecha_creacion DESC);

CREATE INDEX IF NOT EXISTS idx_grupos_transacciones_contraparte
  ON grupos_transacciones(id_contraparte)
  WHERE id_contraparte IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_arqueos_grupo
  ON arqueos(id_grupo_transacciones)
  WHERE id_grupo_transacciones IS NOT NULL;

-- El efectivo fisico compartido se vincula al grupo, no se duplica por transaccion.
ALTER TABLE movimientos_efectivo
  ADD COLUMN IF NOT EXISTS id_grupo_transacciones UUID
    REFERENCES grupos_transacciones(id_grupo_transacciones);

CREATE INDEX IF NOT EXISTS idx_movimientos_efectivo_grupo
  ON movimientos_efectivo(id_grupo_transacciones)
  WHERE id_grupo_transacciones IS NOT NULL;

-- Vista operativa: una fila por grupo y moneda con recibido, entregado, vuelto y diferencia.
DROP VIEW IF EXISTS vw_grupos_transacciones_liquidacion;
CREATE OR REPLACE VIEW vw_grupos_transacciones_liquidacion AS
SELECT
  g.id_grupo_transacciones,
  g.codigo_operacion,
  g.id_turno,
  g.id_contraparte,
  g.estado,
  m.id_moneda,
  m.codigo AS codigo_moneda,
  m.simbolo,
  COALESCE(sum(a.monto_total) FILTER (WHERE a.tipo = 'TRANSACCION_RECIBIDO'), 0) AS monto_recibido,
  COALESCE(sum(a.monto_total) FILTER (WHERE a.tipo = 'TRANSACCION_ENTREGADO'), 0) AS monto_entregado,
  COALESCE(sum(a.monto_total) FILTER (WHERE a.tipo = 'TRANSACCION_VUELTO'), 0) AS monto_vuelto,
  COALESCE(sum(a.monto_esperado) FILTER (WHERE a.tipo = 'TRANSACCION_RECIBIDO'), 0) AS monto_esperado_recibido,
  COALESCE(sum(a.monto_esperado) FILTER (WHERE a.tipo = 'TRANSACCION_ENTREGADO'), 0) AS monto_esperado_entregado,
  COALESCE(sum(a.monto_esperado) FILTER (WHERE a.tipo = 'TRANSACCION_VUELTO'), 0) AS monto_esperado_vuelto,
  COALESCE(sum(a.diferencia) FILTER (WHERE a.tipo = 'TRANSACCION_RECIBIDO'), 0)
    - COALESCE(sum(a.diferencia) FILTER (WHERE a.tipo = 'TRANSACCION_ENTREGADO'), 0)
    - COALESCE(sum(a.diferencia) FILTER (WHERE a.tipo = 'TRANSACCION_VUELTO'), 0) AS diferencia,
  COALESCE(sum(a.monto_total) FILTER (WHERE a.tipo = 'TRANSACCION_RECIBIDO'), 0)
    - COALESCE(sum(a.monto_total) FILTER (WHERE a.tipo = 'TRANSACCION_ENTREGADO'), 0)
    - COALESCE(sum(a.monto_total) FILTER (WHERE a.tipo = 'TRANSACCION_VUELTO'), 0) AS monto_neto
FROM grupos_transacciones g
CROSS JOIN monedas m
LEFT JOIN arqueos a
  ON a.id_grupo_transacciones = g.id_grupo_transacciones
 AND a.id_moneda = m.id_moneda
GROUP BY
  g.id_grupo_transacciones,
  g.codigo_operacion,
  g.id_turno,
  g.id_contraparte,
  g.estado,
  m.id_moneda,
  m.codigo,
  m.simbolo;

COMMENT ON TABLE grupos_transacciones IS
  'Encabezado atomico para una o varias transacciones realizadas por el mismo cliente.';
COMMENT ON COLUMN arqueos.monto_total IS
  'Monto fisico contado; su tipo indica si fue recibido, entregado o devuelto.';
COMMENT ON COLUMN arqueos.monto_esperado IS
  'Monto calculado que se esperaba recibir o entregar antes del conteo fisico.';
COMMENT ON COLUMN arqueos.diferencia IS
  'Diferencia firmada entre monto fisico contado y monto esperado.';
COMMENT ON COLUMN arqueos_denominaciones.montones_25 IS
  'Cantidad de montones completos de 25 billetes o monedas.';
COMMENT ON COLUMN arqueos_denominaciones.sueltos IS
  'Cantidad de billetes o monedas fuera de los montones de 25.';
COMMENT ON COLUMN movimientos_efectivo.id_grupo_transacciones IS
  'Grupo que origino un movimiento de efectivo compartido entre varias transacciones.';
