-- TEMO - Transferencias operativas por turno.

SET search_path TO temo, public;

BEGIN;

INSERT INTO permisos (codigo, nombre, descripcion)
VALUES ('VER_TRANSFERS', 'Ver Transferencias', 'Consultar y registrar transferencias operativas por turno.')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO roles_permisos (id_rol, id_permiso)
SELECT r.id_rol, p.id_permiso FROM roles r JOIN permisos p ON p.codigo='VER_TRANSFERS'
WHERE r.codigo IN ('JEFA','CAJERO') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS transferencias (
  id_transferencia UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo_transferencia BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  id_turno UUID NOT NULL REFERENCES turnos(id_turno),
  tipo medio_monto NOT NULL,
  direccion direccion_monto NOT NULL,
  id_moneda UUID NOT NULL REFERENCES monedas(id_moneda),
  id_cuenta UUID REFERENCES cuentas_bancarias(id_cuenta),
  monto NUMERIC(16, 4) NOT NULL CHECK (monto > 0),
  descripcion TEXT,
  estado estado_registro NOT NULL DEFAULT 'ACTIVO',
  motivo_anulacion TEXT,
  id_usuario_creacion UUID NOT NULL REFERENCES usuarios(id_usuario),
  id_usuario_modificacion UUID REFERENCES usuarios(id_usuario),
  id_usuario_anulacion UUID REFERENCES usuarios(id_usuario),
  fecha_transferencia TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_anulacion TIMESTAMPTZ,
  CONSTRAINT ck_transferencias_tipo CHECK (tipo IN ('EFECTIVO', 'CUENTA_BANCARIA')),
  CONSTRAINT ck_transferencias_cuenta CHECK (
    (tipo = 'EFECTIVO' AND id_cuenta IS NULL)
    OR (tipo = 'CUENTA_BANCARIA' AND id_cuenta IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS transferencias_denominaciones (
  id_transferencia UUID NOT NULL REFERENCES transferencias(id_transferencia) ON DELETE CASCADE,
  id_denominacion UUID NOT NULL REFERENCES denominaciones(id_denominacion),
  montones_25 INTEGER NOT NULL DEFAULT 0 CHECK (montones_25 >= 0),
  sueltos INTEGER NOT NULL DEFAULT 0 CHECK (sueltos >= 0),
  PRIMARY KEY (id_transferencia, id_denominacion)
);

ALTER TABLE movimientos_efectivo
  ADD COLUMN IF NOT EXISTS id_transferencia UUID REFERENCES transferencias(id_transferencia);

ALTER TABLE movimientos_cuentas
  ADD COLUMN IF NOT EXISTS id_transferencia UUID REFERENCES transferencias(id_transferencia);

CREATE INDEX IF NOT EXISTS idx_transferencias_turno_fecha
  ON transferencias(id_turno, fecha_transferencia DESC);
CREATE INDEX IF NOT EXISTS idx_transferencias_cuenta
  ON transferencias(id_cuenta) WHERE id_cuenta IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_movimientos_efectivo_transferencia
  ON movimientos_efectivo(id_transferencia) WHERE id_transferencia IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_movimientos_cuentas_transferencia
  ON movimientos_cuentas(id_transferencia) WHERE id_transferencia IS NOT NULL;

COMMIT;
